from .._dataclass import dataclass
from ..enums import MessageType
from ..flags import MessageFlags
from ..snowflake import Snowflake
from ..utils import ISO8601Timestamp, Nullable, Optional
from .application import Application
from .attachment import Attachment
from .channel import Channel
from .channel_mention import ChannelMention
from .components import Component
from .embed import Embed
from .message_activity import MessageActivity
from .message_call import MessageCall
from .message_interaction import MessageInteraction
from .message_interaction_metadata import MessageInteractionMetadata
from .message_reference import MessageReference
from .message_snapshot import MessageSnapshot
from .poll import Poll
from .reaction import Reaction
from .resolved_data import ResolvedData
from .role_subscription_data import RoleSubscriptionData
from .shared_client_theme import SharedClientTheme
from .sticker import Sticker
from .sticker_item import StickerItem
from .user import User
from typing import Union


@dataclass
class Message:
  """Represents a message sent in a channel within Discord.

  .. important::
      An app will receive empty values in the :attr:`~.content`, :attr:`~.embeds`, :attr:`~.attachments`, and :attr:`~.components` fields while :attr:`~.poll` will be omitted if they have not configured (or been approved for) the :attr:`~discord.flags.GatewayIntents.MESSAGE_CONTENT` privileged intent.
  """

  activity: Optional[MessageActivity]
  """Sent with Rich Presence-related chat embeds."""

  application: Optional[Application]
  """Sent with Rich Presence-related chat embeds."""

  application_id: Optional[Snowflake]
  """If the message is an interaction or application-owned webhook, this is the ID of the application."""

  attachments: list[Attachment]
  """Any attached files that are not referenced in embeds or components.

  .. important::
      An app will receive empty value in the :attr:`~.attachments` field they have not configured (or been approved for) the :attr:`~discord.flags.GatewayIntents.MESSAGE_CONTENT` privileged intent.
  """

  author: User
  """The author of this message (not guaranteed to be a valid user).

  .. note::
      The author object follows the structure of the user object, but is only a valid user in the case where the message is generated by a user or bot user. If the message is generated by a webhook, the author object corresponds to the webhook's ID, username, and avatar. You can tell if a message is generated by a webhook by checking for the :attr:`~.webhook_id` on the message object.
  """

  call: Optional[MessageCall]
  """The call associated with the message."""

  channel_id: Snowflake
  """ID of the channel the message was sent in."""

  components: Optional[list[Component]]
  """Sent if the emssage contains components like buttons, action rows, or other interactive components.

  .. important::
      An app will receive empty values in the :attr:`~.components` field if they have not configured (or been approved for) the :attr:`~discord.flags.GatewayIntents.MESSAGE_CONTENT` privileged intent.
  """

  content: str
  """Contents of the message.

  .. important::
      An app will receive empty value in the :attr:`~.content` field if they have not configured (or been approved for) the :attr:`~discord.flags.GatewayIntents.MESSAGE_CONTENT` privileged intent.
  """

  edited_timestamp: Nullable[ISO8601Timestamp]
  """When this message was edited (or ``None`` if never)."""

  embeds: list[Embed]
  """Any embedded content.

  .. important::
      An app will receive empty value in the :attr:`~.embeds` field if they have not configured (or been approved for) the :attr:`~discord.flags.GatewayIntents.MESSAGE_CONTENT` privileged intent.
  """

  flags: Optional[MessageFlags]
  """Message flags combined as a bitfield."""

  id: Snowflake
  """ID of the message."""

  interaction: Optional[MessageInteraction]
  """Sent if the message is a response to an interaction.

  .. attention::
      Deprecated in favor of :attr:`~.interaction_metadata`.
  """

  interaction_metadata: Optional[MessageInteractionMetadata]
  """Sent if the message is sent as a result of an interaction."""

  mention_channels: Optional[list[ChannelMention]]
  """Channels specifically mentioned in this message.

  .. note::
      Not all channel mentions in a message will appear in :attr:`~.mention_channels`. Only textual channels that are visible to everyine in a public guild will ever be included. Only crossposted messages (via Channel Following) currently include :attr:`~.mention_channels` at all. If no mentions in the message meet these requirements, this field will not be sent.
  """

  mention_everyone: bool
  """Whether this message mentions everyone."""

  mention_roles: list[Snowflake]
  """Roles specifically mentioned in this message."""

  mentions: list[User]
  """User specifically mentioned in the message."""

  message_reference: Optional[MessageReference]
  """Data showing the source of a crosspost, channel follow add, pin, or reply message."""

  message_snapshots: Optional[list[MessageSnapshots]]
  """The message associated with the :attr:`~.message_reference`. This is a minimal subset of fields in a message (e.g. :attr:`~.author` is excluded).

  .. seealso::
      :attr:`~discord.enums.MessageReferenceType`
  """

  nonce: Optional[Union[int, str]]
  """Used for validating a message was sent."""

  pinned: bool
  """Whether this message is pinned."""

  poll: Optional[Poll]
  """A poll!

  .. important::
      :attr:`~.poll` will be omitted if the app have not configured (or been approved for) the :attr:`~discord.flags.GatewayIntents.MESSAGE_CONTENT` privileged intent.
  """

  position: Optional[int]
  """A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a thread, it can be used to estimate the relative position of the message in a thread in company with ``total_message_sent`` on parent thread."""

  reactions: Optional[list[Reaction]]
  """Reactions to the message."""

  referenced_message: Nullable[Message]
  """The message associated with the :attr:`~.message_reference`.

  .. important::
      This field is only returned for messages with a :attr:`~.type` of :attr:`~discord.enums.MessageType.REPLY`, :attr:`~discord.enums.MessageType.THREAD_STARTER_MESSAGE`, or :attr:`~discord.enums.CONTEXT_MENU_COMMAND`. If the message is one of these but the :attr:`~.referenced_message` field is not resent, the backend did not attempt to fetch the message that was being replied to, so its state is unknown. If the field exists but is ``None``, the referenced message was deleted.
  """

  resolved: Optional[ResolvedData]
  """Data for users, members, channels, and roles referenced in this message."""

  role_subscription_data: Optional[RoleSubscriptionData]
  """Data of the role subscription purchase or renewal that prompted this :attr:`~discord.enums.MessageType.ROLE_SUBSCRIPTION_PURCHASE` message."""

  shared_client_theme: Optional[SharedClientTheme]
  """The custom client-side theme shared via the message."""

  sticker_items: Optional[list[StickerItem]]
  """Sent if the message contains stickers."""

  stickers: Optional[list[Sticker]]
  """The stickers sent with the message. **Deprecated**."""

  thread: Optional[Channel]
  """The thread that was started from this message, includes thread member object."""
  
  timestamp: ISO8601Timestamp
  """When this message was sent."""

  tts: bool
  """Whether this was a TTS message."""

  type: MessageType
  """Type of message."""

  webhook_id: Optional[Snowflake]
  """If the message is generated by a webhook, this is the webhook's ID."""